const config = {
  RIGID_BODY_MOVE_TRESHOLD: 0.005,
  RIGID_BODY_AABB_BIAS: 0.11,
  CLIP_BIAS: 0.001,
  GJK_MAX_ITERATIONS_NUM: 64,
  EPA_BIAS: 0.00001,
  CONTACT_BIAS: 0.125,
  CONTACT_TRESHOLD: 0.05,
  CONTACT_MANIFOLD_KEEP_TRESHOLD: 0.001,
  SOLVER_ITERATIONS_NUM : 18,
  USE_CONTACT_CACHE : false
};
export default config;
